# Project Name
TARGET = sparkInit

# Sources
CPP_SOURCES = sparkInit.cpp

# Library Locations
LIBDAISY_DIR = ../../../chleggett/DaisyExamples/libDaisy/
DAISYSP_DIR = ../../../chleggett/DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
